name: Build Wheels

on: [push, pull_request]

jobs:

  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, macos-12, ubuntu-latest]
        py: ["3.7", "3.8", "3.9", "3.10"]
    
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}
          cache: "pip"

      - name: Install pyswmm
        run: |
          pip install -r requirements.txt
          pip install -e .
      
      - name: run unit tests
        run: pytest


      - name: Test wheel
        run: |
          pip install --no-index --find-links=./dist pyswmm
          pytest
  
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install build requirements
        run: pip install -r requirements.txt

      - name: Build wheel
        run: python setup.py sdist bdist_wheel

      - name: Test wheel
        run: |
          pip install --no-index --find-links=./dist pyswmm
          pytest

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ./dist/pyswmm-*.*
      
      # https://github.com/pypa/gh-action-pypi-publish
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
      
      - name: Publish distribution 📦 to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
      